name: paceDataProcessEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0=h57928b3_2
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - affine=2.4.0=pyhd8ed1ab_1
  - aiobotocore=2.25.2=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=pyh4ca1811_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - aniso8601=10.0.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.12.0=pyhcf101f3_0
  - anywidget=0.9.21=pyhd8ed1ab_0
  - aom=3.9.1=he0c23c2_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py314h5a2d7ad_2
  - arrow=1.4.0=pyhcf101f3_0
  - asf_search=11.0.0=pyhd8ed1ab_0
  - asf_search-base=11.0.0=pyhd8ed1ab_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - async-lru=2.0.5=pyh29332c3_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.2=hca034e6_6
  - aws-sdk-cpp=1.11.606=h06ee25a_9
  - azure-core-cpp=1.16.1=h49e36cd_0
  - azure-identity-cpp=1.13.2=hb4e5e84_1
  - azure-storage-blobs-cpp=12.15.0=h32e6b1f_1
  - azure-storage-common-cpp=12.11.0=hb4e5e84_1
  - azure-storage-files-datalake-cpp=12.13.0=h4b0f033_1
  - babel=2.17.0=pyhd8ed1ab_0
  - backports.zstd=1.2.0=py314h680f03e_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - bleach=6.3.0=pyhcf101f3_0
  - bleach-with-css=6.3.0=h5f6438b_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.8.1=pyhd8ed1ab_0
  - botocore=1.40.70=pyhd8ed1ab_0
  - bqplot=0.12.45=pyhe01879c_0
  - branca=0.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py314he701e3d_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - c-blosc2=2.22.0=h2af8807_1
  - ca-certificates=2025.11.12=h4c7d964_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachelib=0.13.0=pyhd8ed1ab_1
  - cachetools=6.2.2=pyhd8ed1ab_0
  - cairo=1.18.4=h5782bbf_0
  - capnproto=1.2.0=h3a793f1_0
  - cartopy=0.25.0=py314hd8fd7ce_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cf_xarray=0.10.9=pyhd8ed1ab_0
  - cffi=2.0.0=py314h5a2d7ad_1
  - cfitsio=4.6.3=h023ae6c_0
  - cftime=1.6.4=py314h2dcd201_2
  - charls=2.4.2=h1537add_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - ciso8601=2.3.3=py314h4667ab5_1
  - click=8.3.1=pyha7b4d00_1
  - click-plugins=1.1.1.2=pyhd8ed1ab_0
  - cligj=0.7.2=pyhd8ed1ab_2
  - cloudpickle=3.1.2=pyhcf101f3_1
  - color-operations=0.2.0=py314h2dcd201_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py314h909e829_3
  - cpython=3.14.2=py314hd8ed1ab_100
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py314h5a2d7ad_1
  - dask=2025.11.0=pyhcf101f3_0
  - dask-core=2025.11.0=pyhcf101f3_0
  - dateparser=1.2.2=pyhd8ed1ab_0
  - dav1d=1.2.1=hcfcfb64_0
  - debugpy=1.8.17=py314hb98de8c_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.3.1=pyhd8ed1ab_0
  - distributed=2025.11.0=pyhcf101f3_0
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=he0c23c2_0
  - earthpy=0.9.4=pyhd8ed1ab_0
  - eval-type-backport=0.3.1=pyhd8ed1ab_0
  - eval_type_backport=0.3.1=pyha770c72_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fiona=1.10.1=py314h13fbf68_4
  - flask=3.1.2=pyhd8ed1ab_0
  - flask-caching=2.3.1=pyhd8ed1ab_0
  - flask-cors=6.0.1=pyhe01879c_0
  - flask-restx=1.3.0=pyhd8ed1ab_1
  - fmt=12.0.0=h29169d4_0
  - folium=0.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.0=pyh7db6752_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=h57928b3_0
  - freexl=2.0.0=hf297d47_2
  - frozenlist=1.7.0=pyhf298e5d_0
  - fsspec=2025.12.0=pyhd8ed1ab_0
  - gdal=3.10.3=py314hc17c739_27
  - gdown=5.2.0=pyhd8ed1ab_1
  - geojson=3.2.0=pyhd8ed1ab_0
  - geopandas=0.14.4=pyhd8ed1ab_0
  - geopandas-base=0.14.4=pyha770c72_0
  - geos=3.14.1=hdade9fe_0
  - geotiff=1.7.4=h73469f5_4
  - giflib=5.2.2=h64bf75a_0
  - google-crc32c=1.7.1=py314h720154c_1
  - graphite2=1.3.14=hac47afa_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.7.3=pyhd8ed1ab_0
  - h5py=3.15.1=nompi_py314hc249e69_101
  - harfbuzz=12.2.0=h5f2951f_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.6=nompi_h89f0904_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he0c23c2_0
  - idna=3.11=pyhd8ed1ab_0
  - imagecodecs=2025.11.11=py314h794b082_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipyevents=2.0.4=pyhbbac1ac_0
  - ipyfilechooser=0.6.0=pyhd8ed1ab_0
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipyleaflet=0.20.0=pyhd8ed1ab_0
  - ipysheet=0.7.0=pyhd8ed1ab_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipytree=0.2.2=pyhd8ed1ab_1
  - ipyvue=1.11.2=pyhd8ed1ab_0
  - ipyvuetify=1.11.3=pyhd8ed1ab_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=pyhcf101f3_3
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_leaflet=0.20.0=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.5.0=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.28.0=pyhcf101f3_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - jxrlib=1.1=hcfcfb64_3
  - kealib=1.6.2=h5949fbd_2
  - kiwisolver=1.4.9=py314hf309875_2
  - krb5=1.21.3=hdf4eb48_0
  - lark=1.3.1=pyhd8ed1ab_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=hbcf6048_0
  - leafmap=0.57.10=pyhd8ed1ab_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libaec=1.1.4=h20038f6_0
  - libarchive=3.8.2=gpl_h26aea39_100
  - libarrow=22.0.0=hc93d987_4_cuda
  - libarrow-acero=22.0.0=h7d8d6a5_4_cuda
  - libarrow-compute=22.0.0=h2db994a_4_cuda
  - libarrow-dataset=22.0.0=h7d8d6a5_4_cuda
  - libarrow-substrait=22.0.0=hf865cc0_4_cuda
  - libavif16=1.3.0=he916da2_2
  - libblas=3.11.0=4_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=4_h2a3cdd5_mkl
  - libclang13=21.1.7=default_ha2db4b5_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.17.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgdal=3.10.3=hafd5c6c_27
  - libgdal-core=3.10.3=h1a28ea4_26
  - libgdal-fits=3.10.3=hdcf1cd7_26
  - libgdal-grib=3.10.3=h8ff101f_26
  - libgdal-hdf4=3.10.3=ha47b6c4_26
  - libgdal-hdf5=3.10.3=h0f01001_26
  - libgdal-jp2openjpeg=3.10.3=hf58e487_26
  - libgdal-kea=3.10.3=hea5172e_26
  - libgdal-netcdf=3.10.3=hbb26ad1_26
  - libgdal-pdf=3.10.3=h2c2eb3f_26
  - libgdal-pg=3.10.3=hc8b3922_26
  - libgdal-postgisraster=3.10.3=hc8b3922_26
  - libgdal-tiledb=3.10.3=h4b49758_26
  - libgdal-xls=3.10.3=h93cc17c_26
  - libglib=2.86.2=hd9c3897_0
  - libgomp=15.2.0=h8ee18e1_16
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h4379cf1_1003
  - libhwy=1.3.0=ha71e874_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libjxl=0.11.1=hac9b6f3_5
  - libkml=1.3.0=h68a222c_1022
  - liblapack=3.11.0=4_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libmpdec=4.0.0=h2466b09_0
  - libnetcdf=4.9.3=nompi_h7d90bef_103
  - libparquet=22.0.0=h7051d1f_4_cuda
  - libpng=1.6.53=h7351971_0
  - libpq=18.1=h7c87ebf_2
  - libprotobuf=6.31.1=hdcda5b4_2
  - libre2-11=2025.11.05=h0eb2380_0
  - librttopo=1.1.0=haa95264_20
  - libsodium=1.0.20=hc70643c_0
  - libspatialindex=2.1.0=h518811d_0
  - libspatialite=5.1.0=gpl_h0cd62ae_119
  - libsqlite=3.51.1=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.2=hb980946_0
  - libvulkan-loader=1.4.328.1=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libxml2-devel=2.15.1=ha29bfb0_0
  - libxslt=1.1.43=h0fbe4c1_1
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h2466b09_2
  - libzopfli=1.0.3=h0e60522_0
  - llvm-openmp=21.1.7=h4fa8253_0
  - localtileserver=0.10.7=pyhd8ed1ab_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py314hfc2a91f_1
  - lz4-c=1.10.0=h2466b09_1
  - lzo=2.10=h6a83c73_1002
  - mapclassify=2.10.0=pyhd8ed1ab_1
  - maplibre=0.3.5=pyhd8ed1ab_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=pyh7db6752_0
  - matplotlib=3.10.8=py314h86ab7b2_0
  - matplotlib-base=3.10.8=py314hfa45d96_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minizip=4.0.10=h9fa1bad_0
  - mistune=3.1.4=pyhcf101f3_0
  - mkl=2025.3.0=hac47afa_454
  - morecantile=7.0.0=pyhd8ed1ab_0
  - msgpack-python=1.1.2=py314h909e829_1
  - multidict=6.7.0=pyh62beb40_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muparser=2.3.5=he0c23c2_0
  - narwhals=2.13.0=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyhcf101f3_1
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.3=nompi_py314h640c526_100
  - networkx=3.6.1=pyhcf101f3_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numcodecs=0.16.5=py314hd8fd7ce_0
  - numexpr=2.14.1=mkl_py314h220b711_1
  - numpy=2.3.5=py314h06c3c77_0
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.0=h725018a_0
  - opera-utils=0.25.3=pyhd8ed1ab_0
  - orc=2.2.1=h7414dfc_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py314hd8fd7ce_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.46=h3402e2f_0
  - pillow=12.0.0=py314h61b30b5_2
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h5112557_1
  - platformdirs=4.5.1=pyhcf101f3_0
  - plotly=6.5.0=pyhd8ed1ab_0
  - pmtiles=3.4.1=pyhd8ed1ab_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - poppler=25.07.0=h813ae87_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=18.1=h4ecb8ce_2
  - proj=9.7.1=h7b1ce8f_0
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=pyhe1237c8_0
  - pscript=0.7.7=pyhd8ed1ab_0
  - psutil=7.1.3=py314hc5dbbe4_0
  - psygnal=0.15.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=22.0.0=py314h86ab7b2_0
  - pyarrow-core=22.0.0=py314hc631f2f_0_cuda
  - pycparser=2.22=pyh29332c3_1
  - pycrs=1.0.2=pyhd8ed1ab_1
  - pydantic=2.12.5=pyhcf101f3_1
  - pydantic-core=2.41.5=py314h9f07db2_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyproj=3.7.2=py314h422fe16_2
  - pyshp=3.0.3=pyhd8ed1ab_0
  - pyside6=6.9.3=py314h2c9462b_1
  - pysocks=1.7.1=pyh09c184e_7
  - pystac=1.14.1=pyhd8ed1ab_0
  - pystac-client=0.9.0=pyhd8ed1ab_0
  - python=3.14.2=h4b44e0e_100_cp314
  - python-box=7.3.2=py314h5a2d7ad_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-duckdb=1.4.3=py314h13fbf68_0
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-gil=3.14.2=h4df99d1_100
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.14=8_cp314
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py314h2dcd201_2
  - pywin32=311=py314h8f8f202_1
  - pywinpty=2.0.15=py314h51f0985_1
  - pyyaml=6.0.3=pyh7db6752_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.9.3=ha0de62e_1
  - rasterio=1.4.3=py314ha070e43_3
  - rav1e=0.7.1=ha073cba_3
  - re2=2025.11.05=ha104f34_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2025.11.3=py314h5a2d7ad_1
  - remotezip=0.12.3=pyhd8ed1ab_1
  - requests=2.32.5=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rich=14.2.0=pyhcf101f3_0
  - rio-cogeo=7.0.0=pyhd8ed1ab_0
  - rio-tiler=8.0.1=pyhd8ed1ab_0
  - rioxarray=0.20.0=pyhd8ed1ab_1
  - rpds-py=0.30.0=py314h9f07db2_0
  - rtree=1.4.1=pyh11ca60a_0
  - ruamel.yaml=0.18.16=py314h5a2d7ad_0
  - ruamel.yaml.clib=0.2.14=py314h5a2d7ad_0
  - s3fs=2025.12.0=pyhd8ed1ab_0
  - scikit-image=0.25.2=py314hd8fd7ce_2
  - scikit-learn=1.7.2=py314h6ca0369_0
  - scooby=0.11.0=pyhd8ed1ab_0
  - send2trash=1.8.3=pyh5737063_1
  - server-thread=0.3.0=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.2=py314h76f3c27_2
  - shtab=1.8.0=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - snuggs=1.4.7=pyhd8ed1ab_2
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - spdlog=1.16.0=h7d890cf_1
  - sqlite=3.51.1=hdb435a2_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=3.1.2=hac47afa_0
  - tbb=2022.3.0=hd094cb3_1
  - tblib=3.2.2=pyhcf101f3_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.10.16=pyhd8ed1ab_0
  - tiledb=2.29.2=ha3836d8_1
  - tinycss2=1.5.1=pyhcf101f3_0
  - tk=8.6.13=h2c6b04d_3
  - toml=0.10.2=pyhcf101f3_3
  - tomli=2.3.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.2=py314h5a2d7ad_2
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.3=pyh332efcf_0
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tyro=1.0.1=pyhd8ed1ab_0
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyha7b4d00_0
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py314h5a2d7ad_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - uriparser=0.9.8=h5a68840_0
  - urllib3=2.6.1=pyhd8ed1ab_0
  - uvicorn=0.38.0=pyh5737063_0
  - vc=14.3=h2b53caa_33
  - vc14_runtime=14.44.35208=h818238b_33
  - vcomp14=14.44.35208=h818238b_33
  - vs2015_runtime=14.44.35208=h38c0c73_33
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=25.10.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.9.0=pyhd8ed1ab_0
  - werkzeug=3.1.4=pyhcf101f3_0
  - whitebox=2.3.6=pyhd8ed1ab_0
  - whiteboxgui=2.3.0=pyhd8ed1ab_1
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - wrapt=1.17.3=py314h5a2d7ad_1
  - xarray=2025.12.0=pyhcf101f3_0
  - xerces-c=3.3.0=he0c23c2_0
  - xorg-libx11=1.8.12=hf48077a_0
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=pyh7db6752_0
  - zarr=3.1.5=pyhcf101f3_0
  - zeromq=4.3.5=h5bddc39_9
  - zfp=1.0.1=h2f0f97f_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h2466b09_2
  - zlib-ng=2.3.2=h5112557_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - scipy==1.16.3
prefix: I:\Stephie\Apps\Anaconda\envs\paceDataProcessEnv
